# This workflows will create a new issue card in Azure DevOPs and update the link in the GitHub issue with the card number once its created
  
name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.AZURE_DEVOPS_ISSUES }}"
          github_token: "${{ secrets.GH_ISSUE_CONN_AB }}"
          ado_organization: "AGW-Delivery"
          ado_project: "Digital Product Delivery"
         # ado_area_path: "optional_area_path\\optional_area_path"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
